### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by LeaVerou** [vintagesucks/instagram-export#8]
Hey, thank you so much for making this!
I've used it successfully for importing my initial instagram data, so it has been a lifesaver!
However, when I tried to run it today (to import some new data), I got the following error:

```
Uncaught ReflectionException: Class string does not exist in /Users/leaverou/Documents/instagram-export2/vendor/netresearch/jsonmapper/src/JsonMapper.php:550
Stack trace:
#0 /Users/leaverou/Documents/instagram-export2/vendor/netresearch/jsonmapper/src/JsonMapper.php(550): ReflectionClass->__construct('string')
#1 /Users/leaverou/Documents/instagram-export2/vendor/netresearch/jsonmapper/src/JsonMapper.php(382): JsonMapper->createInstance('string')
#2 /Users/leaverou/Documents/instagram-export2/vendor/netresearch/jsonmapper/src/JsonMapper.php(265): JsonMapper->mapArray(Array, Array, 'string')
#3 /Users/leaverou/Documents/instagram-export2/vendor/netresearch/jsonmapper/src/JsonMapper.php(280): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\Model\User))
#4 /Users/leaverou/Documents/instagram-export2/vendor/mgp25/instagram-php/src/Client.php(433): JsonMapper->map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse))
#5 /Users/leaverou/Documents/instagram-export2/vendor/mgp25/instagram-p in /Users/leaverou/Documents/instagram-export2/vendor/netresearch/jsonmapper/src/JsonMapper.php on line 5
50
```

I tried it on a fresh copy as well (since mine had a ton of modifications), same error.

Googling the error brought this up which seems relevant: https://github.com/mgp25/Instagram-API/issues/1720

**Comment by vintagesucks** [comment]
I'm glad you found it useful!

Thank you for reporting and also fixing this in #9. I added a ~daily~ cron job to the Travis Build to catch errors related to outdated dependencies automatically.
